// ── Syllabus courses ──────────────────────────────────────────────────────────
export const COURSES = [
  { id: 'math',      name: 'Mathematics for ML & AI',       number: 1 },
  { id: 'prog',      name: 'Programming Foundations',        number: 2 },
  { id: 'eda',       name: 'Data Analysis & EDA',            number: 3 },
  { id: 'ml',        name: 'Classical Machine Learning',     number: 4 },
  { id: 'dl',        name: 'Deep Learning',                  number: 5 },
  { id: 'nlp',       name: 'Natural Language Processing',    number: 6 },
  { id: 'cv',        name: 'Computer Vision (Advanced)',     number: 7 },
  { id: 'ts',        name: 'Time Series & Forecasting',      number: 8 },
  { id: 'rl',        name: 'Reinforcement Learning',         number: 9 },
  { id: 'mlsys',     name: 'ML Systems & Software Eng.',     number: 10 },
  { id: 'mlops',     name: 'MLOps & Production ML',          number: 11 },
  { id: 'llmops',    name: 'LLMOps & Generative AI Eng.',    number: 12 },
  { id: 'feat',      name: 'Advanced Feature Eng. & AutoML', number: 13 },
  { id: 'interp',    name: 'ML Interpretability',            number: 14 },
  { id: 'stats',     name: 'Statistical Inference & Causal', number: 15 },
  { id: 'sysdesign', name: 'ML System Design',               number: 16 },
  { id: 'de',        name: 'Data Engineering for ML',        number: 17 },
  { id: 'spec',      name: 'Specialized & Emerging Areas',   number: 18 },
  { id: 'gpu',       name: 'GPU Systems & High-Perf AI',     number: 19 },
  { id: 'recsys',    name: 'Recommendation Systems & Search',number: 20 },
  { id: 'aisec',     name: 'AI Security & Safety Eng.',      number: 21 },
  { id: 'dist',      name: 'Distributed Systems & Backend',  number: 22 },
  { id: 'linux',     name: 'Linux, Networking & DevOps',     number: 23 },
  { id: 'datacentric','name': 'Data-Centric AI & Synthetic', number: 24 },
  { id: 'genai',     name: 'Advanced GenAI & Reasoning',     number: 25 },
  { id: 'prodrel',   name: 'Production Reliability & AIOps', number: 26 },
  { id: 'research',  name: 'Research Engineering',           number: 27 },
  { id: 'edgeai',    name: 'Edge AI & On-Device ML',         number: 28 },
  { id: 'career',    name: 'Career & Portfolio Engineering', number: 29 },
]

// ── Default topics (pre-seeded on first login) ────────────────────────────────
export const DEFAULT_TOPICS = [
  // Math
  { name: 'Linear algebra fundamentals', course_id: 'math', course_name: 'Mathematics for ML & AI' },
  { name: 'Calculus & optimization',     course_id: 'math', course_name: 'Mathematics for ML & AI' },
  { name: 'Probability & statistics',    course_id: 'math', course_name: 'Mathematics for ML & AI' },
  { name: 'Information theory basics',   course_id: 'math', course_name: 'Mathematics for ML & AI' },
  { name: 'Discrete math & graph theory',course_id: 'math', course_name: 'Mathematics for ML & AI' },
  // Programming
  { name: 'Python core & OOP',           course_id: 'prog', course_name: 'Programming Foundations' },
  { name: 'DSA — arrays, trees, graphs', course_id: 'prog', course_name: 'Programming Foundations' },
  { name: 'SQL — window functions, CTEs',course_id: 'prog', course_name: 'Programming Foundations' },
  { name: 'NumPy & Pandas advanced',     course_id: 'prog', course_name: 'Programming Foundations' },
  { name: 'Scientific Python stack',     course_id: 'prog', course_name: 'Programming Foundations' },
  // EDA
  { name: 'EDA & data wrangling',        course_id: 'eda', course_name: 'Data Analysis & EDA' },
  { name: 'Feature engineering',         course_id: 'eda', course_name: 'Data Analysis & EDA' },
  { name: 'A/B testing & experimentation',course_id:'eda', course_name: 'Data Analysis & EDA' },
  { name: 'Data validation frameworks',  course_id: 'eda', course_name: 'Data Analysis & EDA' },
  // Classical ML
  { name: 'Regression algorithms',       course_id: 'ml', course_name: 'Classical Machine Learning' },
  { name: 'Classification algorithms',   course_id: 'ml', course_name: 'Classical Machine Learning' },
  { name: 'Unsupervised learning',        course_id: 'ml', course_name: 'Classical Machine Learning' },
  { name: 'Model evaluation & CV',        course_id: 'ml', course_name: 'Classical Machine Learning' },
  { name: 'Hyperparameter tuning',        course_id: 'ml', course_name: 'Classical Machine Learning' },
  { name: 'XGBoost, LightGBM, CatBoost', course_id: 'ml', course_name: 'Classical Machine Learning' },
  // Deep Learning
  { name: 'Neural network foundations',  course_id: 'dl', course_name: 'Deep Learning' },
  { name: 'CNNs & computer vision',      course_id: 'dl', course_name: 'Deep Learning' },
  { name: 'RNNs, LSTMs, GRUs',           course_id: 'dl', course_name: 'Deep Learning' },
  { name: 'Transformers & attention',    course_id: 'dl', course_name: 'Deep Learning' },
  { name: 'PyTorch training loops',      course_id: 'dl', course_name: 'Deep Learning' },
  { name: 'Distributed training (DDP, FSDP)', course_id: 'dl', course_name: 'Deep Learning' },
  // NLP
  { name: 'Text preprocessing & embeddings', course_id: 'nlp', course_name: 'Natural Language Processing' },
  { name: 'Classical NLP tasks',         course_id: 'nlp', course_name: 'Natural Language Processing' },
  { name: 'Large language models (GPT, BERT)', course_id: 'nlp', course_name: 'Natural Language Processing' },
  { name: 'LLM fine-tuning (LoRA, QLoRA)', course_id: 'nlp', course_name: 'Natural Language Processing' },
  // CV
  { name: 'Generative models (GANs, Diffusion)', course_id: 'cv', course_name: 'Computer Vision (Advanced)' },
  { name: 'Multimodal models (CLIP, BLIP)', course_id: 'cv', course_name: 'Computer Vision (Advanced)' },
  { name: 'Model optimization for deployment', course_id: 'cv', course_name: 'Computer Vision (Advanced)' },
  // Time Series
  { name: 'Classical methods (ARIMA, Prophet)', course_id: 'ts', course_name: 'Time Series & Forecasting' },
  { name: 'DL for time series (TFT, N-BEATS)', course_id: 'ts', course_name: 'Time Series & Forecasting' },
  { name: 'Probabilistic forecasting',   course_id: 'ts', course_name: 'Time Series & Forecasting' },
  // RL
  { name: 'RL foundations (MDPs, Q-learning)', course_id: 'rl', course_name: 'Reinforcement Learning' },
  { name: 'Deep RL (PPO, SAC, DQN)',     course_id: 'rl', course_name: 'Reinforcement Learning' },
  { name: 'RLHF for LLMs',              course_id: 'rl', course_name: 'Reinforcement Learning' },
  // ML Systems
  { name: 'Software engineering for ML', course_id: 'mlsys', course_name: 'ML Systems & Software Eng.' },
  { name: 'Data engineering basics',     course_id: 'mlsys', course_name: 'ML Systems & Software Eng.' },
  { name: 'Cloud platforms (AWS/GCP/Azure)', course_id: 'mlsys', course_name: 'ML Systems & Software Eng.' },
  // MLOps
  { name: 'Experiment tracking (MLflow, W&B)', course_id: 'mlops', course_name: 'MLOps & Production ML' },
  { name: 'Docker & containerization',   course_id: 'mlops', course_name: 'MLOps & Production ML' },
  { name: 'Kubernetes basics',           course_id: 'mlops', course_name: 'MLOps & Production ML' },
  { name: 'CI/CD for ML pipelines',     course_id: 'mlops', course_name: 'MLOps & Production ML' },
  { name: 'Model serving (FastAPI, Triton)', course_id: 'mlops', course_name: 'MLOps & Production ML' },
  { name: 'Monitoring & drift detection', course_id: 'mlops', course_name: 'MLOps & Production ML' },
  // LLMOps
  { name: 'Prompt engineering',          course_id: 'llmops', course_name: 'LLMOps & Generative AI Eng.' },
  { name: 'RAG system design',           course_id: 'llmops', course_name: 'LLMOps & Generative AI Eng.' },
  { name: 'LLM application frameworks', course_id: 'llmops', course_name: 'LLMOps & Generative AI Eng.' },
  { name: 'LLM inference optimization', course_id: 'llmops', course_name: 'LLMOps & Generative AI Eng.' },
  { name: 'LLM evaluation & safety',    course_id: 'llmops', course_name: 'LLMOps & Generative AI Eng.' },
  // Feature Eng
  { name: 'Advanced feature engineering', course_id: 'feat', course_name: 'Advanced Feature Eng. & AutoML' },
  { name: 'AutoML systems (AutoGluon, FLAML)', course_id: 'feat', course_name: 'Advanced Feature Eng. & AutoML' },
  // Interpretability
  { name: 'SHAP & interpretability',    course_id: 'interp', course_name: 'ML Interpretability' },
  { name: 'Responsible AI & fairness',  course_id: 'interp', course_name: 'ML Interpretability' },
  // Stats
  { name: 'Statistical inference (Bayesian/Frequentist)', course_id: 'stats', course_name: 'Statistical Inference & Causal' },
  { name: 'Causal inference basics',    course_id: 'stats', course_name: 'Statistical Inference & Causal' },
  // System Design
  { name: 'ML system design — recommendation', course_id: 'sysdesign', course_name: 'ML System Design' },
  { name: 'ML system design — fraud detection', course_id: 'sysdesign', course_name: 'ML System Design' },
  { name: 'ML system design — search ranking', course_id: 'sysdesign', course_name: 'ML System Design' },
  { name: 'ML system design — ads CTR',course_id: 'sysdesign', course_name: 'ML System Design' },
  { name: 'Data infrastructure (Lambda/Kappa arch)', course_id: 'sysdesign', course_name: 'ML System Design' },
  // Data Engineering
  { name: 'Apache Spark & PySpark',     course_id: 'de', course_name: 'Data Engineering for ML' },
  { name: 'Kafka & stream processing',  course_id: 'de', course_name: 'Data Engineering for ML' },
  { name: 'Feature stores (Feast, Tecton)', course_id: 'de', course_name: 'Data Engineering for ML' },
  // Specialized
  { name: 'Graph ML (GCN, GraphSAGE, GAT)', course_id: 'spec', course_name: 'Specialized & Emerging Areas' },
  { name: 'Audio & speech ML',          course_id: 'spec', course_name: 'Specialized & Emerging Areas' },
  { name: 'Tabular deep learning',      course_id: 'spec', course_name: 'Specialized & Emerging Areas' },
  { name: 'AI agents & agentic systems', course_id: 'spec', course_name: 'Specialized & Emerging Areas' },
  // GPU
  { name: 'CUDA & GPU programming basics', course_id: 'gpu', course_name: 'GPU Systems & High-Perf AI' },
  { name: 'Model quantization & pruning', course_id: 'gpu', course_name: 'GPU Systems & High-Perf AI' },
  // Rec Systems
  { name: 'Collaborative filtering',    course_id: 'recsys', course_name: 'Recommendation Systems & Search' },
  { name: 'Two-tower & embedding models', course_id: 'recsys', course_name: 'Recommendation Systems & Search' },
  { name: 'Vector search & ANN',        course_id: 'recsys', course_name: 'Recommendation Systems & Search' },
  // AI Security & Safety (21)
  { name: 'Adversarial attacks & defenses',     course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },
  { name: 'Model robustness & stress testing',  course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },
  { name: 'AI red-teaming & jailbreak analysis',course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },
  { name: 'Differential privacy in ML',         course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },
  { name: 'Federated learning fundamentals',    course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },
  { name: 'AI governance & compliance (EU AI Act)', course_id: 'aisec', course_name: 'AI Security & Safety Eng.' },

  // Distributed Systems & Backend (22)
  { name: 'Distributed systems fundamentals (CAP, consensus)', course_id: 'dist', course_name: 'Distributed Systems & Backend' },
  { name: 'gRPC & REST API design',             course_id: 'dist', course_name: 'Distributed Systems & Backend' },
  { name: 'Message queues (Kafka, RabbitMQ)',   course_id: 'dist', course_name: 'Distributed Systems & Backend' },
  { name: 'Microservices & service mesh',       course_id: 'dist', course_name: 'Distributed Systems & Backend' },
  { name: 'Database sharding & replication',    course_id: 'dist', course_name: 'Distributed Systems & Backend' },

  // Linux, Networking & DevOps (23)
  { name: 'Linux CLI & shell scripting',        course_id: 'linux', course_name: 'Linux, Networking & DevOps' },
  { name: 'Networking fundamentals (TCP/IP, DNS, HTTP)', course_id: 'linux', course_name: 'Linux, Networking & DevOps' },
  { name: 'Terraform & Infrastructure as Code', course_id: 'linux', course_name: 'Linux, Networking & DevOps' },
  { name: 'GitHub Actions & CI/CD pipelines',   course_id: 'linux', course_name: 'Linux, Networking & DevOps' },
  { name: 'System monitoring & observability',  course_id: 'linux', course_name: 'Linux, Networking & DevOps' },

  // Data-Centric AI & Synthetic (24)
  { name: 'Data quality & labeling strategies', course_id: 'datacentric', course_name: 'Data-Centric AI & Synthetic' },
  { name: 'Synthetic data generation (SDV, CTGAN)', course_id: 'datacentric', course_name: 'Data-Centric AI & Synthetic' },
  { name: 'Data augmentation techniques',       course_id: 'datacentric', course_name: 'Data-Centric AI & Synthetic' },
  { name: 'Active learning & human-in-the-loop',course_id: 'datacentric', course_name: 'Data-Centric AI & Synthetic' },
  { name: 'Data versioning (DVC, lakeFS)',       course_id: 'datacentric', course_name: 'Data-Centric AI & Synthetic' },

  // Advanced GenAI & Reasoning (25)
  { name: 'Chain-of-thought & reasoning prompting', course_id: 'genai', course_name: 'Advanced GenAI & Reasoning' },
  { name: 'Multimodal LLMs (GPT-4V, Gemini, LLaVA)', course_id: 'genai', course_name: 'Advanced GenAI & Reasoning' },
  { name: 'Constitutional AI & RLAIF',          course_id: 'genai', course_name: 'Advanced GenAI & Reasoning' },
  { name: 'Long-context LLMs & memory systems', course_id: 'genai', course_name: 'Advanced GenAI & Reasoning' },
  { name: 'Mixture of Experts (MoE) architecture', course_id: 'genai', course_name: 'Advanced GenAI & Reasoning' },

  // Production Reliability & AIOps (26)
  { name: 'SLOs, SLAs & error budgets',         course_id: 'prodrel', course_name: 'Production Reliability & AIOps' },
  { name: 'Incident response for ML systems',   course_id: 'prodrel', course_name: 'Production Reliability & AIOps' },
  { name: 'Log aggregation (ELK, Grafana, Prometheus)', course_id: 'prodrel', course_name: 'Production Reliability & AIOps' },
  { name: 'Chaos engineering for ML pipelines', course_id: 'prodrel', course_name: 'Production Reliability & AIOps' },
  { name: 'Cloud cost optimization for ML',     course_id: 'prodrel', course_name: 'Production Reliability & AIOps' },

  // Research Engineering (27)
  { name: 'Paper reading & critical analysis',  course_id: 'research', course_name: 'Research Engineering' },
  { name: 'Experiment design & ablation studies', course_id: 'research', course_name: 'Research Engineering' },
  { name: 'Reproducibility in ML research',     course_id: 'research', course_name: 'Research Engineering' },
  { name: 'Benchmarking & evaluation frameworks', course_id: 'research', course_name: 'Research Engineering' },
  { name: 'Open-source research contribution',  course_id: 'research', course_name: 'Research Engineering' },

  // Edge AI & On-Device ML (28)
  { name: 'TensorFlow Lite & ONNX Runtime',     course_id: 'edgeai', course_name: 'Edge AI & On-Device ML' },
  { name: 'Model compression (pruning, distillation)', course_id: 'edgeai', course_name: 'Edge AI & On-Device ML' },
  { name: 'Quantization-aware training',        course_id: 'edgeai', course_name: 'Edge AI & On-Device ML' },
  { name: 'Mobile deployment (CoreML, Android NNAPI)', course_id: 'edgeai', course_name: 'Edge AI & On-Device ML' },
  { name: 'WebAssembly & browser-side ML',      course_id: 'edgeai', course_name: 'Edge AI & On-Device ML' },

  // Career (29)
  { name: 'Resume & LinkedIn optimization', course_id: 'career', course_name: 'Career & Portfolio Engineering' },
  { name: 'ML system design interviews', course_id: 'career', course_name: 'Career & Portfolio Engineering' },
  { name: 'Kaggle strategy & competitions', course_id: 'career', course_name: 'Career & Portfolio Engineering' },
  { name: 'Open-source contribution strategy', course_id: 'career', course_name: 'Career & Portfolio Engineering' },
]

// ── 178 Companies ─────────────────────────────────────────────────────────────
export const PRESET_COMPANIES = [
  // Tier 1 — Big Tech MNCs
  { name:'Google India',       tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad', salary_range:'₹40–90 LPA',   difficulty:'Hard',        roles:'Applied Scientist, MLE, DS', is_preset:true },
  { name:'Microsoft India',    tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore', salary_range:'₹35–80 LPA',   difficulty:'Medium-Hard', roles:'MLE, DS, Research', is_preset:true },
  { name:'Amazon India',       tier:'Big Tech',    tier_number:1, work_mode:'WFO',     india_cities:'Hyderabad, Bangalore, Chennai', salary_range:'₹30–75 LPA', difficulty:'Medium-Hard', roles:'Applied Scientist, MLE', is_preset:true },
  { name:'Meta India',         tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹35–80 LPA',   difficulty:'Hard',        roles:'MLE, DS, ML Infra', is_preset:true },
  { name:'Apple India',        tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore', salary_range:'₹35–90 LPA', difficulty:'Medium-Hard', roles:'MLE, DS', is_preset:true },
  { name:'NVIDIA India',       tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Pune, Bangalore', salary_range:'₹40–100 LPA',  difficulty:'Medium-Hard', roles:'ML Systems, DL Eng', is_preset:true },
  { name:'Adobe India',        tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Noida', salary_range:'₹30–70 LPA',   difficulty:'Medium',      roles:'DS, MLE, AI Eng', is_preset:true },
  { name:'Salesforce India',   tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore', salary_range:'₹28–65 LPA', difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'SAP India',          tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹22–55 LPA', difficulty:'Medium', roles:'DS, MLE', is_preset:true },
  { name:'Oracle India',       tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore, Pune', salary_range:'₹22–55 LPA', difficulty:'Medium', roles:'DS, MLE', is_preset:true },
  { name:'IBM India',          tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, AI Eng', is_preset:true },
  { name:'Intel India',        tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad', salary_range:'₹25–60 LPA', difficulty:'Medium', roles:'ML Eng, Edge AI', is_preset:true },
  { name:'Qualcomm India',     tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore', salary_range:'₹28–65 LPA', difficulty:'Medium-Hard', roles:'On-device AI, MLE', is_preset:true },
  { name:'Cisco India',        tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹22–55 LPA', difficulty:'Medium', roles:'MLE, DS', is_preset:true },
  { name:'PayPal India',       tier:'Big Tech',    tier_number:1, work_mode:'Hybrid',  india_cities:'Bangalore, Chennai', salary_range:'₹22–50 LPA', difficulty:'Medium', roles:'DS, MLE, Fraud ML', is_preset:true },
  // Tier 2 — AI Labs
  { name:'Sarvam AI',          tier:'AI Lab',      tier_number:2, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–70 LPA',   difficulty:'Medium-Hard', roles:'MLE, Research, NLP', is_preset:true },
  { name:'Krutrim AI',         tier:'AI Lab',      tier_number:2, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–65 LPA',   difficulty:'Medium-Hard', roles:'MLE, AI Eng', is_preset:true },
  { name:'Google DeepMind',    tier:'AI Lab',      tier_number:2, work_mode:'Hybrid',  india_cities:'Bangalore (some roles)', salary_range:'₹60–150 LPA', difficulty:'Hard', roles:'Research Scientist, MLE', is_preset:true },
  { name:'OpenAI',             tier:'AI Lab',      tier_number:2, work_mode:'Remote',  india_cities:'Remote/Relocation', salary_range:'Remote USD', difficulty:'Hard', roles:'MLE, Research', is_preset:true },
  { name:'Anthropic',          tier:'AI Lab',      tier_number:2, work_mode:'Remote',  india_cities:'Remote/Relocation', salary_range:'Remote USD', difficulty:'Hard', roles:'MLE, Research, Safety', is_preset:true },
  { name:'Cohere',             tier:'AI Lab',      tier_number:2, work_mode:'Remote',  india_cities:'Remote', salary_range:'₹40–80 LPA',   difficulty:'Medium-Hard', roles:'MLE, NLP Eng', is_preset:true },
  { name:'Hugging Face',       tier:'AI Lab',      tier_number:2, work_mode:'Remote',  india_cities:'Remote (global)', salary_range:'₹40–80 LPA', difficulty:'Medium-Hard', roles:'MLE, ML Research', is_preset:true },
  { name:'AI4Bharat',          tier:'AI Lab',      tier_number:2, work_mode:'Hybrid',  india_cities:'Chennai (IIT Madras)', salary_range:'₹15–35 LPA', difficulty:'Medium', roles:'Research, NLP', is_preset:true },
  { name:'NVIDIA Research India',tier:'AI Lab',    tier_number:2, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹50–120 LPA', difficulty:'Hard', roles:'Research Scientist, MLE', is_preset:true },
  { name:'TII (Falcon LLM)',   tier:'AI Lab',      tier_number:2, work_mode:'Hybrid',  india_cities:'Remote/Abu Dhabi', salary_range:'AED equiv ₹40–90 LPA', difficulty:'Medium-Hard', roles:'LLM Research, MLE', is_preset:true },
  // Tier 3 — Indian Unicorns
  { name:'Flipkart',           tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹30–75 LPA',   difficulty:'Medium-Hard', roles:'MLE, DS, Search', is_preset:true },
  { name:'Swiggy',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–60 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'Zomato',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹22–55 LPA', difficulty:'Medium', roles:'MLE, DS', is_preset:true },
  { name:'Ola',                tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹20–50 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'Dream11',            tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Mumbai', salary_range:'₹22–55 LPA',     difficulty:'Medium',      roles:'MLE, DS, Sports Analytics', is_preset:true },
  { name:'ShareChat / Moj',    tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹20–50 LPA',   difficulty:'Medium',      roles:'MLE, NLP, DS', is_preset:true },
  { name:'Meesho',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹22–50 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'CRED',               tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–60 LPA',   difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Paytm',              tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Noida, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium',  roles:'DS, MLE, Fraud', is_preset:true },
  { name:'Byju\'s',            tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–40 LPA',   difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  { name:'Nykaa',              tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹18–40 LPA', difficulty:'Approachable', roles:'DS, MLE', is_preset:true },
  { name:'Lenskart',           tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹18–40 LPA', difficulty:'Approachable', roles:'DS, CV', is_preset:true },
  { name:'Urban Company',      tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Gurugram', salary_range:'₹18–40 LPA',    difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  { name:'Juspay',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹20–48 LPA',   difficulty:'Medium',      roles:'MLE, DS, Payments', is_preset:true },
  { name:'InMobi',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹20–50 LPA',   difficulty:'Medium',      roles:'MLE, DS, Ads', is_preset:true },
  { name:'Freshworks',         tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Chennai, Bangalore', salary_range:'₹20–50 LPA', difficulty:'Medium', roles:'MLE, NLP', is_preset:true },
  { name:'Zepto',              tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Mumbai', salary_range:'₹18–45 LPA',     difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Bigbasket',          tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–42 LPA',   difficulty:'Approachable',roles:'DS, Supply Chain ML', is_preset:true },
  { name:'Groww',              tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'DS, Risk ML', is_preset:true },
  { name:'Rapido',             tier:'Unicorn',     tier_number:3, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹16–38 LPA',   difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  // Tier 4 — Fintech
  { name:'PhonePe',            tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–65 LPA',   difficulty:'Medium-Hard', roles:'DS, MLE, Fraud', is_preset:true },
  { name:'Razorpay',           tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'DS, MLE, Risk', is_preset:true },
  { name:'BharatPe',           tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, Credit ML', is_preset:true },
  { name:'Pine Labs',          tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, Analytics', is_preset:true },
  { name:'Slice',              tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–40 LPA',   difficulty:'Medium',      roles:'DS, Credit ML', is_preset:true },
  { name:'MobiKwik',           tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Gurugram', salary_range:'₹15–35 LPA',    difficulty:'Approachable',roles:'DS, Fraud ML', is_preset:true },
  { name:'KreditBee',          tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹15–38 LPA',   difficulty:'Approachable',roles:'DS, Risk ML', is_preset:true },
  { name:'Policybazaar',       tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, MLE', is_preset:true },
  { name:'Perfios',            tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–42 LPA',   difficulty:'Medium',      roles:'DS, Credit ML', is_preset:true },
  { name:'Setu',               tier:'Fintech',     tier_number:4, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–40 LPA',   difficulty:'Approachable',roles:'DS, Analytics', is_preset:true },
  // Tier 5 — E-commerce
  { name:'Myntra',             tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹25–60 LPA',   difficulty:'Medium',      roles:'MLE, DS, Visual Search', is_preset:true },
  { name:'Ajio',               tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹22–50 LPA', difficulty:'Medium',  roles:'DS, MLE', is_preset:true },
  { name:'JioMart',            tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹22–50 LPA', difficulty:'Medium',  roles:'DS, Supply Chain ML', is_preset:true },
  { name:'Udaan',              tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹20–50 LPA',   difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Delhivery',          tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, Logistics ML', is_preset:true },
  { name:'Shiprocket',         tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Gurugram', salary_range:'₹15–38 LPA',    difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  { name:'Snapdeal',           tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Gurugram', salary_range:'₹15–35 LPA',    difficulty:'Approachable',roles:'DS, Recommendation', is_preset:true },
  { name:'IndiaMART',          tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Noida', salary_range:'₹15–35 LPA',      difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  { name:'Walmart Global Tech',tier:'E-commerce',  tier_number:5, work_mode:'Hybrid',  india_cities:'Bangalore, Chennai', salary_range:'₹28–65 LPA', difficulty:'Medium',  roles:'MLE, DS, Supply Chain', is_preset:true },
  // Tier 6 — Global Finance
  { name:'Goldman Sachs India',tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad', salary_range:'₹25–75 LPA', difficulty:'Medium-Hard', roles:'Quant, MLE, DS', is_preset:true },
  { name:'JPMorgan India',     tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Hyderabad', salary_range:'₹22–60 LPA', difficulty:'Medium', roles:'DS, Risk ML, NLP', is_preset:true },
  { name:'Morgan Stanley India',tier:'Finance',    tier_number:6, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹22–60 LPA', difficulty:'Medium',  roles:'Risk ML, NLP', is_preset:true },
  { name:'Citi India',         tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune, Mumbai, Chennai', salary_range:'₹20–55 LPA', difficulty:'Medium', roles:'DS, Fraud ML', is_preset:true },
  { name:'Deutsche Bank India',tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune, Bangalore', salary_range:'₹20–55 LPA',  difficulty:'Medium',      roles:'Risk ML, Compliance NLP', is_preset:true },
  { name:'HSBC India',         tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune, Bangalore, Hyderabad', salary_range:'₹18–50 LPA', difficulty:'Medium', roles:'AML ML, DS', is_preset:true },
  { name:'D.E. Shaw India',    tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹30–90 LPA',    difficulty:'Hard',        roles:'Quant ML, Research', is_preset:true },
  { name:'Two Sigma India',    tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹35–90 LPA',    difficulty:'Hard',        roles:'Quant ML, Research', is_preset:true },
  { name:'Optiver India',      tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹30–80 LPA',    difficulty:'Hard',        roles:'Quant, HFT ML', is_preset:true },
  { name:'American Express India',tier:'Finance',  tier_number:6, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹20–55 LPA', difficulty:'Medium', roles:'DS, Credit ML', is_preset:true },
  { name:'Mastercard India',   tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune, Gurugram', salary_range:'₹20–55 LPA',  difficulty:'Medium',      roles:'DS, Fraud ML', is_preset:true },
  { name:'Visa India',         tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹22–58 LPA',    difficulty:'Medium',      roles:'DS, Fraud ML', is_preset:true },
  { name:'Bloomberg India',    tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune', salary_range:'₹22–60 LPA',         difficulty:'Medium-Hard', roles:'NLP Eng, DS', is_preset:true },
  { name:'Barclays India',     tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Pune, Chennai', salary_range:'₹18–50 LPA', difficulty:'Medium',      roles:'DS, Risk ML', is_preset:true },
  { name:'Fidelity India',     tier:'Finance',     tier_number:6, work_mode:'Hybrid',  india_cities:'Bangalore, Chennai', salary_range:'₹18–48 LPA', difficulty:'Medium',  roles:'DS, Portfolio ML', is_preset:true },
  // Tier 7 — Analytics & Consulting
  { name:'Axtria',             tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Gurugram, Bangalore', salary_range:'₹12–35 LPA', difficulty:'Medium', roles:'DS, Senior DS, Pharma Analytics', is_preset:true },
  { name:'ZS Associates',      tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Gurugram, Pune, Bangalore', salary_range:'₹14–40 LPA', difficulty:'Medium', roles:'DA Associate, DS', is_preset:true },
  { name:'Mu Sigma',           tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹12–30 LPA',    difficulty:'Medium',      roles:'Decision Scientist', is_preset:true },
  { name:'Fractal Analytics',  tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Gurugram', salary_range:'₹14–40 LPA', difficulty:'Medium', roles:'DS, MLE, AI Eng', is_preset:true },
  { name:'Tiger Analytics',    tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Chennai, Bangalore', salary_range:'₹14–38 LPA', difficulty:'Medium',  roles:'DS, MLE', is_preset:true },
  { name:'Sigmoid',            tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹14–40 LPA',    difficulty:'Medium',      roles:'MLE, MLOps, Data Eng', is_preset:true },
  { name:'Latent View Analytics',tier:'Analytics', tier_number:7, work_mode:'Hybrid',  india_cities:'Chennai, Bangalore', salary_range:'₹12–32 LPA', difficulty:'Medium',  roles:'DS, Analytics', is_preset:true },
  { name:'EXL Service',        tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Noida, Bangalore, Hyderabad', salary_range:'₹12–32 LPA', difficulty:'Medium', roles:'DS, Insurance ML', is_preset:true },
  { name:'WNS Analytics',      tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Pune', salary_range:'₹12–30 LPA', difficulty:'Approachable', roles:'DS, Analytics', is_preset:true },
  { name:'McKinsey QuantumBlack',tier:'Consulting', tier_number:7, work_mode:'Hybrid', india_cities:'Gurugram, Mumbai', salary_range:'₹35–90 LPA', difficulty:'Medium-Hard', roles:'DS, Applied ML', is_preset:true },
  { name:'BCG GAMMA / X',      tier:'Consulting',  tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Gurugram', salary_range:'₹35–90 LPA', difficulty:'Medium-Hard', roles:'DS, AI Eng', is_preset:true },
  { name:'Deloitte India AI',  tier:'Consulting',  tier_number:7, work_mode:'Hybrid',  india_cities:'Hyderabad, Mumbai, Bangalore', salary_range:'₹18–50 LPA', difficulty:'Medium', roles:'DS, AI Consultant', is_preset:true },
  { name:'Accenture AI',       tier:'Consulting',  tier_number:7, work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹15–45 LPA', difficulty:'Medium', roles:'DS, MLE, AI Eng', is_preset:true },
  { name:'Capgemini India',    tier:'Consulting',  tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Pune, Chennai', salary_range:'₹14–40 LPA', difficulty:'Medium', roles:'DS, MLE', is_preset:true },
  { name:'IQVIA India',        tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Hyderabad', salary_range:'₹14–38 LPA', difficulty:'Medium', roles:'DS, RWE Analyst, Pharma ML', is_preset:true },
  { name:'Ipsos India',        tier:'Analytics',   tier_number:7, work_mode:'Hybrid',  india_cities:'Mumbai, Gurugram', salary_range:'₹12–28 LPA', difficulty:'Approachable', roles:'DS, Market Research ML', is_preset:true },
  // Tier 8 — IT Services
  { name:'TCS AI & Cognitive', tier:'IT Services', tier_number:8, work_mode:'WFO',     india_cities:'Pan-India', salary_range:'₹8–22 LPA',     difficulty:'Approachable',roles:'DS, MLE, AI Eng', is_preset:true },
  { name:'Infosys AI',         tier:'IT Services', tier_number:8, work_mode:'WFO',     india_cities:'Bangalore, Pune, Hyderabad', salary_range:'₹8–25 LPA', difficulty:'Approachable', roles:'DS, MLE', is_preset:true },
  { name:'Wipro AI',           tier:'IT Services', tier_number:8, work_mode:'WFO',     india_cities:'Bangalore, Hyderabad, Chennai', salary_range:'₹8–22 LPA', difficulty:'Approachable', roles:'DS, MLE', is_preset:true },
  { name:'HCLTech',            tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Noida, Bangalore, Chennai', salary_range:'₹8–22 LPA',  difficulty:'Approachable',roles:'DS, MLE', is_preset:true },
  { name:'Cognizant AI',       tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Chennai, Bangalore, Hyderabad', salary_range:'₹8–25 LPA', difficulty:'Approachable', roles:'DS, GenAI Eng', is_preset:true },
  { name:'Mphasis DeepInsights',tier:'IT Services',tier_number:8, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹12–30 LPA',    difficulty:'Medium',      roles:'DS, BFSI ML', is_preset:true },
  { name:'Tech Mahindra',      tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Pune, Hyderabad, Bangalore', salary_range:'₹10–28 LPA', difficulty:'Approachable', roles:'DS, MLE', is_preset:true },
  { name:'LTIMindtree',        tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore, Pune', salary_range:'₹12–30 LPA',  difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Persistent Systems', tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Pune, Bangalore, Hyderabad', salary_range:'₹12–32 LPA', difficulty:'Medium',     roles:'DS, MLE', is_preset:true },
  { name:'Hexaware',           tier:'IT Services', tier_number:8, work_mode:'Hybrid',  india_cities:'Mumbai, Chennai, Bangalore', salary_range:'₹10–28 LPA', difficulty:'Approachable', roles:'DS, Analytics', is_preset:true },
  // Tier 9 — Healthcare
  { name:'Niramai',            tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹15–38 LPA',   difficulty:'Medium-Hard', roles:'CV Eng, MLE', is_preset:true },
  { name:'Qure.ai',            tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Mumbai', salary_range:'₹18–50 LPA',       difficulty:'Medium-Hard', roles:'CV Eng, MLE, Research', is_preset:true },
  { name:'Siemens Healthineers',tier:'Healthcare', tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore, Mumbai', salary_range:'₹20–50 LPA', difficulty:'Medium-Hard', roles:'Medical Imaging ML', is_preset:true },
  { name:'Philips Innovation Campus',tier:'Healthcare',tier_number:9,work_mode:'Hybrid',india_cities:'Bangalore', salary_range:'₹20–55 LPA', difficulty:'Medium', roles:'Medical Imaging ML', is_preset:true },
  { name:'MedGenome',          tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹15–38 LPA',   difficulty:'Medium-Hard', roles:'Genomics ML, Bioinformatics', is_preset:true },
  { name:'Practo',             tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–45 LPA',   difficulty:'Medium',      roles:'DS, Clinical NLP', is_preset:true },
  { name:'1mg (Tata)',         tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Gurugram', salary_range:'₹18–42 LPA',    difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Apollo Hospitals AI',tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Hyderabad, Bangalore', salary_range:'₹15–38 LPA', difficulty:'Medium', roles:'DS, Clinical ML', is_preset:true },
  { name:'Acko Insurance',     tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–45 LPA',   difficulty:'Medium',      roles:'DS, Actuarial ML', is_preset:true },
  { name:'Innovaccer',         tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Noida', salary_range:'₹20–55 LPA',       difficulty:'Medium',      roles:'DS, Health NLP', is_preset:true },
  { name:'Eka Care',           tier:'Healthcare',  tier_number:9, work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹15–38 LPA',   difficulty:'Medium',      roles:'DS, Health NLP', is_preset:true },
  // Tier 10 — SaaS & B2B
  { name:'Zoho',               tier:'SaaS & B2B',  tier_number:10,work_mode:'WFO',     india_cities:'Chennai, Bangalore, Pune', salary_range:'₹12–32 LPA', difficulty:'Medium',   roles:'DS, MLE, Zia AI', is_preset:true },
  { name:'MoEngage',           tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–45 LPA',   difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'CleverTap',          tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹18–42 LPA', difficulty:'Medium',    roles:'DS, MLE', is_preset:true },
  { name:'Chargebee',          tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Chennai', salary_range:'₹18–45 LPA',     difficulty:'Medium',      roles:'DS, Revenue ML', is_preset:true },
  { name:'Darwinbox',          tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹18–42 LPA',   difficulty:'Medium',      roles:'DS, HR ML', is_preset:true },
  { name:'Uniphore',           tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Chennai, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium',  roles:'NLP Eng, ASR', is_preset:true },
  { name:'Yellow.ai',          tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–45 LPA',   difficulty:'Medium',      roles:'NLP Eng, MLE', is_preset:true },
  { name:'Postman',            tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'BrowserStack',       tier:'SaaS & B2B',  tier_number:10,work_mode:'Hybrid',  india_cities:'Mumbai, Bangalore', salary_range:'₹20–50 LPA', difficulty:'Medium',  roles:'MLE, DS', is_preset:true },
  // Tier 11 — Media & Gaming
  { name:'Hotstar',            tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai, Bangalore', salary_range:'₹22–55 LPA', difficulty:'Medium',  roles:'MLE, DS, Recommendation', is_preset:true },
  { name:'Jio Cinema',         tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai', salary_range:'₹20–50 LPA',     difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Zee Entertainment',  tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai', salary_range:'₹18–40 LPA',     difficulty:'Approachable',roles:'DS, Analytics', is_preset:true },
  { name:'Nazara Technologies',tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai', salary_range:'₹18–45 LPA',     difficulty:'Medium',      roles:'DS, Gaming ML', is_preset:true },
  { name:'MPL',                tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹20–50 LPA',  difficulty:'Medium',      roles:'MLE, DS, Fraud', is_preset:true },
  { name:'Games24x7',          tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai, Bangalore', salary_range:'₹18–45 LPA', difficulty:'Medium', roles:'DS, Gaming ML', is_preset:true },
  { name:'upGrad',             tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Mumbai, Bangalore', salary_range:'₹16–40 LPA', difficulty:'Medium',  roles:'DS, NLP', is_preset:true },
  { name:'Vedantu',            tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹15–38 LPA',  difficulty:'Approachable',roles:'DS, Adaptive ML', is_preset:true },
  { name:'Unacademy',          tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹15–38 LPA',  difficulty:'Approachable',roles:'DS, NLP', is_preset:true },
  { name:'Times Internet',     tier:'Media & Gaming',tier_number:11,work_mode:'Hybrid', india_cities:'Gurugram', salary_range:'₹15–38 LPA',   difficulty:'Medium',      roles:'DS, NLP, Recommendation', is_preset:true },
  // Tier 12 — Automotive & Deep Tech
  { name:'Tata Motors AI',     tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Pune', salary_range:'₹18–45 LPA',        difficulty:'Medium',      roles:'DS, EV ML', is_preset:true },
  { name:'Mahindra Digital',   tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Mumbai, Pune', salary_range:'₹16–40 LPA', difficulty:'Medium',      roles:'DS, MLE', is_preset:true },
  { name:'Ather Energy',       tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore', salary_range:'₹18–45 LPA',   difficulty:'Medium',      roles:'MLE, Battery ML', is_preset:true },
  { name:'Bosch India (RBEI)', tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Coimbatore', salary_range:'₹18–50 LPA', difficulty:'Medium-Hard', roles:'MLE, ADAS, Industrial AI', is_preset:true },
  { name:'Continental India',  tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Chennai', salary_range:'₹16–42 LPA', difficulty:'Medium-Hard', roles:'CV Eng, ADAS ML', is_preset:true },
  { name:'Siemens Digital Ind.',tier:'Automotive', tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Pune, Mumbai', salary_range:'₹18–50 LPA', difficulty:'Medium-Hard', roles:'Industrial AI, MLOps', is_preset:true },
  { name:'ABB India',          tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Vadodara', salary_range:'₹16–42 LPA', difficulty:'Medium',   roles:'Industrial ML, DS', is_preset:true },
  { name:'Honeywell India',    tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Chennai', salary_range:'₹18–48 LPA', difficulty:'Medium', roles:'DS, Industrial IoT ML', is_preset:true },
  { name:'GE Aerospace India', tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹18–50 LPA', difficulty:'Medium', roles:'Pred. Maintenance ML, DS', is_preset:true },
  { name:'Rivian India',       tier:'Automotive',  tier_number:12,work_mode:'Hybrid',  india_cities:'Hyderabad', salary_range:'₹20–52 LPA',   difficulty:'Medium',      roles:'MLE, DS, EV', is_preset:true },
  // Tier 13 — Semiconductor
  { name:'NVIDIA India (detailed)',tier:'Semiconductor',tier_number:13,work_mode:'Hybrid',india_cities:'Pune, Bangalore, Hyderabad', salary_range:'₹40–100 LPA', difficulty:'Medium-Hard', roles:'ML Systems, CUDA, DL Eng', is_preset:true },
  { name:'AMD India',          tier:'Semiconductor',tier_number:13,work_mode:'Hybrid', india_cities:'Hyderabad, Bangalore', salary_range:'₹28–70 LPA', difficulty:'Medium-Hard', roles:'ML on ROCm, HW-aware ML', is_preset:true },
  { name:'Arm India',          tier:'Semiconductor',tier_number:13,work_mode:'Hybrid', india_cities:'Bangalore, Hyderabad, Pune', salary_range:'₹25–65 LPA', difficulty:'Medium-Hard', roles:'Edge ML, Neural Processor', is_preset:true },
  { name:'Micron India',       tier:'Semiconductor',tier_number:13,work_mode:'Hybrid', india_cities:'Hyderabad', salary_range:'₹20–55 LPA',   difficulty:'Medium',      roles:'Yield ML, Process ML', is_preset:true },
  { name:'Texas Instruments India',tier:'Semiconductor',tier_number:13,work_mode:'Hybrid',india_cities:'Bangalore', salary_range:'₹20–55 LPA', difficulty:'Medium-Hard', roles:'Embedded ML, TinyML', is_preset:true },
  { name:'MediaTek India',     tier:'Semiconductor',tier_number:13,work_mode:'Hybrid', india_cities:'Bangalore, Hyderabad', salary_range:'₹22–60 LPA', difficulty:'Medium-Hard', roles:'Mobile ML, APU', is_preset:true },
  { name:'Samsung SSIR',       tier:'Semiconductor',tier_number:13,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹25–65 LPA',   difficulty:'Medium-Hard', roles:'On-device AI, MLE', is_preset:true },
  // Tier 14 — Cloud & Data Infra
  { name:'Databricks India',   tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹35–85 LPA',   difficulty:'Medium-Hard', roles:'MLE, MLOps, Data Eng', is_preset:true },
  { name:'Snowflake India',    tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore, Hyderabad', salary_range:'₹30–75 LPA', difficulty:'Medium', roles:'DS, MLE, Cortex AI', is_preset:true },
  { name:'Confluent India',    tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹28–65 LPA',   difficulty:'Medium',      roles:'MLOps, Data Eng', is_preset:true },
  { name:'MongoDB India',      tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore, Hyderabad', salary_range:'₹25–60 LPA', difficulty:'Medium', roles:'MLE, DS', is_preset:true },
  { name:'Elastic India',      tier:'Cloud & Infra',tier_number:14,work_mode:'Remote', india_cities:'Bangalore', salary_range:'₹25–60 LPA',   difficulty:'Medium',      roles:'MLE, Search ML', is_preset:true },
  { name:'Datadog India',      tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore, Hyderabad', salary_range:'₹28–65 LPA', difficulty:'Medium', roles:'MLE, Observability ML', is_preset:true },
  { name:'ThoughtWorks India', tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore, Pune, Hyderabad, Chennai', salary_range:'₹18–50 LPA', difficulty:'Medium', roles:'MLE, MLOps', is_preset:true },
  { name:'Harness',            tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹25–60 LPA',   difficulty:'Medium',      roles:'MLOps, Platform Eng', is_preset:true },
  { name:'Hasura',             tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'Samsara India',      tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'MLE, IoT ML', is_preset:true },
  { name:'Palantir India',     tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore (some roles)', salary_range:'₹30–70 LPA', difficulty:'Medium-Hard', roles:'MLE, DS, Foundry', is_preset:true },
  { name:'Rubrik India',       tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹28–68 LPA',   difficulty:'Medium',      roles:'MLE, DS', is_preset:true },
  { name:'Palo Alto Networks', tier:'Cloud & Infra',tier_number:14,work_mode:'Hybrid', india_cities:'Bangalore', salary_range:'₹28–65 LPA',   difficulty:'Medium-Hard', roles:'Security ML, MLE', is_preset:true },
  { name:'CrowdStrike India',  tier:'Cloud & Infra',tier_number:14,work_mode:'Remote', india_cities:'Bangalore', salary_range:'₹25–62 LPA',   difficulty:'Medium-Hard', roles:'Security ML, MLE', is_preset:true },
  { name:'dbt Labs',           tier:'Cloud & Infra',tier_number:14,work_mode:'Remote', india_cities:'Remote', salary_range:'₹22–55 LPA',      difficulty:'Medium',      roles:'Analytics Eng, MLOps', is_preset:true },
  { name:'Fivetran India',     tier:'Cloud & Infra',tier_number:14,work_mode:'Remote', india_cities:'Bangalore', salary_range:'₹22–55 LPA',   difficulty:'Medium',      roles:'Data Eng, MLE', is_preset:true },
]

// ── Goal categories (default per user) ───────────────────────────────────────
export const DEFAULT_CATEGORIES = [
  { name: 'DSA',        color: '#639922' },
  { name: 'ML / DL',   color: '#7F77DD' },
  { name: 'MLOps',     color: '#EF9F27' },
  { name: 'NLP / LLM', color: '#0C447C' },
  { name: 'System Design', color: '#D85A30' },
  { name: 'Career',    color: '#D4537E' },
  { name: 'Portfolio', color: '#1D9E75' },
  { name: 'Reading',   color: '#888780' },
  { name: 'General',   color: '#888780' },
]

// ── Utility maps ──────────────────────────────────────────────────────────────
export const STATUS_LABEL = {
  not_started: 'Not started',
  in_progress: 'In progress',
  done: 'Done',
}

export const APP_STATUS_LABEL = {
  watchlist:    'Watchlist',
  applied:      'Applied',
  interviewing: 'Interviewing',
  offered:      'Offered',
  rejected:     'Rejected',
}

export const DIFFICULTY_EMOJI = {
  'Hard':        '🔴',
  'Medium-Hard': '🟠',
  'Medium':      '🟡',
  'Approachable':'🟢',
}

export const TIERS = [
  'Big Tech', 'AI Lab', 'Unicorn', 'Fintech', 'E-commerce',
  'Finance', 'Analytics', 'Consulting', 'IT Services', 'Healthcare',
  'SaaS & B2B', 'Media & Gaming', 'Automotive', 'Semiconductor', 'Cloud & Infra', 'Custom',
]

export const INDIA_CITIES = [
  'Bangalore', 'Hyderabad', 'Pune', 'Gurugram', 'Noida',
  'Mumbai', 'Chennai', 'Delhi', 'Remote', 'Pan-India',
]
